server:
  port: 8085

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GauravVasdev/fun-learn-configuration
          clone-on-start: true